project_id = "tlnjspsywycbudhewsfv"

[functions.stripe-create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-manage-subscription]
verify_jwt = false

[functions.populate-municipios-ibge]
verify_jwt = false

[functions.sync-user-subscription]
verify_jwt = false

[functions.mercadopago-create-pix]
verify_jwt = false

[functions.mercadopago-create-link]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.mercadopago-connect]
verify_jwt = false

[functions.mercadopago-disconnect]
verify_jwt = false

[functions.mp-create-validation-payment]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.google-calendar-connect]
verify_jwt = false

[functions.google-calendar-callback]
verify_jwt = false

[functions.google-calendar-sync]
verify_jwt = false

[functions.google-calendar-disconnect]
verify_jwt = false

[functions.google-calendar-sync-all]
verify_jwt = false
